### ISSUE TITLE
Fails with large values in memcached

### ISSUE THREAD

**Issue by samfrench** [comandeo/crystal-memcached#9]
The client seems to fail when we get and set large values in memcached. This is shown by a failing test I have added:
> https://github.com/samfrench/crystal-memcached/blob/large-value-test/spec/memcached/client_spec.cr#L11-L17

We tried with Dalli ruby client to get and set the same value in the same memcached instance and that worked fine. So this has been limited to just this client only.

We have looked into the code and tried to provide a fix for this, but do not understand the logic around getting and setting values in memcached. So raising this issue as this will probably be much easier to fix for you than us.

**Comment by comandeo** [comment]
@samfrench Thank you for raising the issue, I'm going to take a look.

**Comment by comandeo** [comment]
@samfrench I think I fixed the problem. Could you please check if it works for you now? Thanks!

**Comment by samfrench** [comment]
Thank you @comandeo. When I run the specs they pass. I am still getting an error with my application as only puts 8164 characters in the cache which is a truncated output. I am currently investigating why this is. If I can't solve it I'll try and get a failing test to replicate the scenario as it might be something I am doing incorrectly.

**Comment by samfrench** [comment]
It actually looks like our large value we are putting into memcached has a non-utf8 character. This is now where the value is breaking for us, so this issue has been resolved as we can now put large values into memcached and retrieve them. Thank you for the quick fix @comandeo as this allows us to progress further with our application.

**Comment by comandeo** [comment]
@samfrench Thanks for the feedback, I am closing this issue.
However, you gave me some food for thoughts. Values in memcached seems to be just bytes - https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped#data-types Maybe it is a good idea to allow clients to operate with slices, but not strings as values. Something like

``` crystal
def get(key : String) : Slice(UInt8)?
```
